version: '3'

services:
  scraper:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    command: python -m sreality

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 159357lol
      POSTGRES_DB: postgres

  server:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    command: python -m server
    ports:
      - '8080:8080'
