version: '3'
services:
  scraper:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      - POSTGRES_HOST=db
      - DISPLAY=:99  # Set the display environment variable for running Chrome
    volumes:
      - ./data:/app/data
    networks:
      - app-network
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    depends_on:
      - db
    environment:
      - POSTGRES_HOST=db
    networks:
      - app-network
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=159357lol
      - POSTGRES_DB=postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network
networks:
  app-network:
volumes:
  db-data: